### ISSUE TITLE
imagej-utils dependency

### ISSUE THREAD

**Issue by tischi** [K-Meech/crosshair#3]
@K-Meech 
I added the imagej-utils dependency to your repository (pom).

1. Please try to remove the copied code from you repo and let me know whether that works.
2. We have to discuss how to ship the imagej-utils to your update site (this is different from having it work locally for you).

**Comment by K-Meech** [comment]
Thanks @tischi - I'll try this out later in the week, and let you know how it goes

**Comment by K-Meech** [comment]
I can't seem to find the imagej-utils dependency - it errors with 'Dependency de.embl.cba:imagej-utils:0.5.3 not found'.  Do I need to list another repository in the pom?

**Comment by K-Meech** [comment]
Adding the repository https://dl.bintray.com/tischi/snapshots resolves this - as in the mobie pom https://github.com/mobie/mobie-viewer-fiji/blob/master/pom.xml#L122

**Comment by K-Meech** [comment]
Spoke too soon - still has issues finding the pom. Errors with 'Failure to find de.embl.cba:imagej-utils:pom:0.5.3 in https://dl.bintray.com/tischi/snapshots'. Any ideas @tischi?

**Comment by K-Meech** [comment]
Jar is in maven.scijava.org - changing name to -SNAPSHOT works: https://github.com/K-Meech/crosshair/commit/2dbc1b11e5c41c32aa5645d1444514c7626348e8

**Comment by imagejan** [comment]
@K-Meech wrote:
> changing name to -SNAPSHOT works

This is because @tischi didn't cut a new release since it is deployed to the scijava maven repo.
@tischi once you cut a release (using `release-version.sh` as usual), this repo can depend on a non-SNAPSHOT version without having to skip the enforcer.
